// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZil0ZnYFfhpfzAPiWaiVtsnZu0vbZNTo',
    appId: '1:502512835451:web:970704ef23ea3dae313bde',
    messagingSenderId: '502512835451',
    projectId: 'task-manager-186d3',
    authDomain: 'task-manager-186d3.firebaseapp.com',
    storageBucket: 'task-manager-186d3.appspot.com',
    measurementId: 'G-CQG3NMNCF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeFpa_yer53T2upUTaoMC8wbzSjdsWn7Q',
    appId: '1:502512835451:android:5a7f7c970b2544d8313bde',
    messagingSenderId: '502512835451',
    projectId: 'task-manager-186d3',
    storageBucket: 'task-manager-186d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfjaz7k-m0dd_t3xBsezy6bsMynsb-2Ro',
    appId: '1:502512835451:ios:0e70e415e278a348313bde',
    messagingSenderId: '502512835451',
    projectId: 'task-manager-186d3',
    storageBucket: 'task-manager-186d3.appspot.com',
    iosBundleId: 'com.ips.ticket.manager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfjaz7k-m0dd_t3xBsezy6bsMynsb-2Ro',
    appId: '1:502512835451:ios:9b99892022b5276c313bde',
    messagingSenderId: '502512835451',
    projectId: 'task-manager-186d3',
    storageBucket: 'task-manager-186d3.appspot.com',
    iosBundleId: 'com.example.ticketManager.RunnerTests',
  );
}
